pool:
  vmImage: windows-latest

stages:
- stage: Build
  jobs:
  - job: Windows_Build
    steps:
    - task: UseDotNet@2
      displayName: 'Use .Net Core runtime 3.1.x'
      inputs:
        packageType: runtime
        version: 3.1.3

    - task: gitversion/setup@0
      inputs:
        versionSpec: '5.x'

    - task: gitversion/execute@0
      displayName: Use GitVersion
      inputs:
        updateAssemblyInfo: 'False'
        useConfigFile: true
    
    - task: MSBuild@1
      inputs:
        solution: Certificate.Generator.sln
        configuration: Release
        platform: Any CPU
        restoreNugetPackages: true
        msbuildArguments: /p:PackageOutputPath=$(Build.ArtifactStagingDirectory)
    
    - publish: $(Build.ArtifactStagingDirectory)
      artifact: Packages

- stage: Release
  jobs:
  - job: NuGet
    steps:
    - download: current
      artifact: Packages

    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: 5.8.0

    - task: NuGetCommand@2
      inputs:
        command: push
        publishFeedCredentials: 'NuGet.org - nventive'
        packagesToPush: $(Pipeline.Workspace)/Packages/*.nupkg